### PR TITLE
Achieve spiritual enlightenment

### PR DESCRIPTION
**Pull request by slice**
Would gitdemocracy be opposed to the inclusion of holy text in their repository?

### CODE REVIEW

**Comment by NotNite** [comment]
Why give this meta?

**Comment by NotNite** [comment]
@ThatNerdyPikachu, the bot's borked

**Comment by aveao** [comment]
@NotNite we're working on it

**Comment by ThatNerdyPikachu** [comment]
@NotNite It's not -- that's intended. I'm going to change the label it's given from ``meta`` to ``manual review required for merge``.

**Comment by aveao** [comment]
Review successful :3

**Comment by ThatNerdyPikachu** [comment]
2:-1, merging...

**Pull request merged**
