### PR TITLE
Add 3 more girls to girls.md

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
This issue will be in voting until (roughly) ``Thu, 09 Apr 2020 15:51:20 EDT``.

**Comment by lun-4** [comment]
Hmm........ Girl........ Me like.

**Comment by ThatNerdyPikachu** [comment]
@aveao Should the bot also assign you? Forget if we went over that.

**Comment by lun-4** [comment]
MORE GIRL;............................. Likey.

**Comment by ThatNerdyPikachu** [comment]
3:0, merging...

**Pull request merged**
